<?php

/* GridShib SAML Tools demo configuration for TG08
 */

// set to TRUE for debug messages in the browser window:
$DEBUG = FALSE;

// user directories will be created in this directory:
$TMPDIR = '/tmp/gridshib-saml-tools';

// environment variables:
$JAVA_HOME = '/opt/java/jdk1.5.0_11';
//$ANT_HOME = '/opt/ant/apache-ant-1.7.0';  // unused
$GRIDSHIB_HOME = '/usr/local/gridshib-saml-tools-0_3_0';

// shell commands (absolute paths recommended):
$CAT = 'cat';
$OPENSSL = 'openssl';

?>